travis:
  secure:
    BINSTAR_TOKEN: aZZPTst1+NB5cEWOKrFcec6sjaA1ymeFRJropSOHo+mc+l4oDcvqxiLP2HSnT3psq35oOtAge2sJMsQ1dhHIBx9BZL1SXKFweR/txoZMeMsCbuL7uuLsOqhSlq0eozFuQA4MasXSRCQW+tFpNdigZ+sB4paGwoSvd3Plpu3tfhh1wGd4/FnBHJkJXWoyBC/pfA0VVfpuKHUIAIoQXqqXGDKIOkqy+NTH0sFgvvrx+nStNlcDx590tFpDavrwPlSmmjf5qDTL/VNyReP+JC2hNuAr5EGEqnYprqijb1+lOtym3dqgY3uLlVqF3GHMZD0x6fOhV/C+EsDwCigOg/KEM49l+4H6f8knhu0wX0w9n+F1UEzBfpv+INGlvuRvIELby1Cxbin9/1AZYqmClhN9sD19vGZ1i619KzRJWUHqsIMADS0Bxzl61D2PM/DBnBAYqumMAt8xURA25UD5jkxi2SSpRHAEYRpME5rWUiau0/N1RmZDj9GtMgmw/txKAclVxAVmnHlen/KTo/0LSj340yN5w9Xrra12+7ihWzz5S6vUZD18BL3vfXVpigeW2COIl+Zxq+sEInm01HfbDZTZU+PgS59wi84CVKoO7vjLQ1zByeXoFaIs+eqAklBH8T3t6cPZCQCpMMDDZxbClbUE5DzGmcdMMrpFL1ci1wO7/UU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
